### PR TITLE
428 display different messages for different choices

### PR DESCRIPTION
**Pull request by Dankco**
## Summary

#428 

- Changed answer text to reflect different choices with a map
- Made option for multiple answers

## Screenshots
image

### CODE REVIEW

**Comment by lawtlee** [comment]
For the second question in Exercise 2 there is a color mismatch when selecting the correct answer

**Comment by Dankco** [comment]
Good catch, I didn't realize the `in` operator only applies to mapped types in typescript...
https://stackoverflow.com/questions/50214731/what-does-the-in-keyword-do-in-typescript

**Comment by lawtlee** [comment]
Do i need to wait for the linter to finish before merging and closing this?

**Comment by Dankco** [comment]
Technically yes but it runs pretty quickly anyway

**Review by lawtlee — APPROVED** [review]

**Pull request merged**
