### PR TITLE
90 update sidebar

### LINKED ISSUE #90: Minor Update: Update Sidebar
image
Update the sidebar to look like it does in the Figma. Note that this should probably be done after #85 is merged

### PR DESCRIPTION
**Pull request by ajtadeo**
## Summary

Closes #90 

- imported Material UI icon package
- implemented slide-in animation and styling for sidebar menu
- menu items are placeholders for future lesson and exercise pages, we may have to update these titles and href links in the future (especially for exercise pages)

### CODE REVIEW

**Review by Dankco — CHANGES_REQUESTED** [review]
Sorry, I didn't realize that the Figma didn't include the Home/Demo pages in the sidebar. Can you add those entries back in along with an entry for the pointer motivation page?
Also, this header here has a cursor: pointer style. Did you intend to make this clickable? If so, I think that this can redirect to the home page. Otherwise, you should probably get rid of it.
image
Nice job with the sidebar overall! It looks a lot cleaner and more colorful!

**Comment by ajtadeo** [comment]
- added yellow bar for selected dropdowns
- removed inline styling, migrated to ./src/styles/Sidebar.scss
- linked "Parcel Pointers" to home
- added Demo, Error page for development only -> remove this later!

**Review by Dankco — COMMENTED** [review]
One last thing here:
With height styling
image
Without height styling:
image
Basically, what is happening is the button is getting cut off, so the icon looks off center. I think the easiest way to solve this is by making the header actually take the size of the button in absolute pixels, but it doesn't exactly make sense for all screens. Different screen sizes are always such a mess to deal with...
Also, there are some merge conflicts that I can resolve or you can resolve- it's up to you.

**Review by Dankco — APPROVED** [review]
Looks good!

**Comment by ajtadeo** [comment]
I only merged the conflicts in that commit, I didn't do the height fix. Should I still work on that issue? @Dankco

**Comment by Dankco** [comment]
Oh, I didn't realize. Let me double check if its an issue in the main deployment.

**Comment by Dankco** [comment]
Yeah, it looks like it got resolved when you merged in the main branch @ajtadeo That's why I thought you fixed it. No need to work on it.

**Pull request merged**
